// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterFilterBusiness.DAL;

#nullable disable

namespace WaterFilterBusiness.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240502140858_AddedCompletionFieldToScheduledCall")]
    partial class AddedCompletionFieldToScheduledCall
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<int>("PermissionsId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.ClientDebt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateOnly?>("CompletedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DeadlineAt")
                        .HasColumnType("date");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("ClientDebts", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.ClientMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Afternotes")
                        .HasMaxLength(210)
                        .HasColumnType("nvarchar(210)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("InitialNotes")
                        .HasMaxLength(210)
                        .HasColumnType("nvarchar(210)");

                    b.Property<int?>("MeetingOutcomeId")
                        .HasColumnType("int");

                    b.Property<int?>("PhoneOperatorId")
                        .HasColumnType("int");

                    b.Property<int>("SalesAgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("MeetingOutcomeId");

                    b.HasIndex("PhoneOperatorId");

                    b.HasIndex("SalesAgentId");

                    b.ToTable("SalesAgentsMeetings", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<bool?>("IsQualified")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)");

                    b.Property<DateTime?>("RedListedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.CustomerCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OutcomeId")
                        .HasColumnType("int");

                    b.Property<int>("PhoneAgentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OutcomeId");

                    b.HasIndex("PhoneAgentId");

                    b.ToTable("CustomerCallsHistory", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.CustomerChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("OldAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OldIsQualified")
                        .HasColumnType("bit");

                    b.Property<string>("OldPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldProfession")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerChangesHistory", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.ScheduledCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PhoneAgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("PhoneAgentId");

                    b.ToTable("ScheduledCalls", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CommissionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(210)
                        .HasColumnType("nvarchar(210)");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommissionTypeId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Commissions", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.CommissionRequest", b =>
                {
                    b.Property<int>("CommissionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CommissionId");

                    b.ToTable("CommissionRequests", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Enums.CallOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CallOutcomes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Name = "Excessive argument"
                        },
                        new
                        {
                            Id = 2,
                            Name = "No answer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rescheduled"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Success"
                        });
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Enums.CommissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("CommissionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Customer added by sales agent"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Monthly sales target reached"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monthly-payment contract created"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Upfront contract payment"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Water filter installed"
                        });
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Enums.DayOfWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("DaysOfWeek", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Name = "Friday"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monday"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Saturday"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Sunday"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thursday"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tuesday"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wednesday"
                        });
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Enums.InventoryRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("InventoryRequestStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Name = "In progress"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        });
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Enums.InventoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("InventoryTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Name = "Big inventory"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Small inventory"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Technician inventory"
                        });
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Enums.MeetingOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("MeetingOutcomes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Name = "Agent cancelled"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Client cancelled"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Failed"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Successful"
                        });
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Enums.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Full payment upfront"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Monthly payments"
                        });
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.BigInventoryItem", b =>
                {
                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ToolId");

                    b.ToTable("BigInventoryItems", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.InventoryItemMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromInventoryId")
                        .HasColumnType("int");

                    b.Property<int>("GiverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("ToInventoryId")
                        .HasColumnType("int");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromInventoryId");

                    b.HasIndex("GiverId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("ToInventoryId");

                    b.HasIndex("ToolId");

                    b.ToTable("InventoryItemMovements", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.InventoryPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.ToTable("InventoryPurchases", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.InventoryRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConcludedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConclusionNote")
                        .HasMaxLength(210)
                        .HasColumnType("nvarchar(210)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RequestNote")
                        .HasMaxLength(210)
                        .HasColumnType("nvarchar(210)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("ToolId");

                    b.ToTable("InventoryRequests", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.SmallInventoryItem", b =>
                {
                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ToolId");

                    b.ToTable("SmallInventoryItems", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.SmallInventoryRequest", b =>
                {
                    b.Property<int>("InventoryRequestId")
                        .HasColumnType("int");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.HasKey("InventoryRequestId");

                    b.HasIndex("RequesterId");

                    b.ToTable("SmallInventoryRequests", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.TechnicianInventoryItem", b =>
                {
                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("TechnicianId", "ToolId");

                    b.HasIndex("ToolId")
                        .IsUnique();

                    b.ToTable("TechnicianInventoryItems", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.TechnicianInventoryRequest", b =>
                {
                    b.Property<int>("InventoryRequestId")
                        .HasColumnType("int");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("InventoryRequestId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("TechnicianInventoryRequests", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ReadUsers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CreateUser"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DeleteUser"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ReadInventoryItems"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CreateInventoryItem"
                        },
                        new
                        {
                            Id = 6,
                            Name = "DeleteInventoryItem"
                        },
                        new
                        {
                            Id = 7,
                            Name = "UpdateInventoryItem"
                        },
                        new
                        {
                            Id = 8,
                            Name = "ReadInventoryPurchases"
                        },
                        new
                        {
                            Id = 9,
                            Name = "CreateInventoryPurchase"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ReadInventoryRequests"
                        },
                        new
                        {
                            Id = 11,
                            Name = "CreateInventoryRequest"
                        },
                        new
                        {
                            Id = 12,
                            Name = "UpdateInventoryRequest"
                        },
                        new
                        {
                            Id = 13,
                            Name = "DeleteInventoryRequest"
                        },
                        new
                        {
                            Id = 14,
                            Name = "ReadCustomers"
                        },
                        new
                        {
                            Id = 15,
                            Name = "CreateCustomer"
                        },
                        new
                        {
                            Id = 16,
                            Name = "UpdateCustomer"
                        },
                        new
                        {
                            Id = 17,
                            Name = "ReadCustomerMeetings"
                        },
                        new
                        {
                            Id = 18,
                            Name = "CreateCustomerMeeting"
                        },
                        new
                        {
                            Id = 19,
                            Name = "UpdateCustomerMeeting"
                        },
                        new
                        {
                            Id = 20,
                            Name = "ReadSales"
                        },
                        new
                        {
                            Id = 21,
                            Name = "CreateSale"
                        },
                        new
                        {
                            Id = 22,
                            Name = "UpdateSale"
                        },
                        new
                        {
                            Id = 23,
                            Name = "AccessPerformanceMetricsStatistics"
                        },
                        new
                        {
                            Id = 24,
                            Name = "AccessOperationalMetricsStatistics"
                        });
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "3",
                            Name = "Chief of Operations",
                            NormalizedName = "CHIEF OF OPERATIONS"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "2",
                            Name = "Inventory manager",
                            NormalizedName = "INVENTORY MANAGER"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "4",
                            Name = "Marketing Chief",
                            NormalizedName = "MARKETING CHIEF"
                        },
                        new
                        {
                            Id = 7,
                            ConcurrencyStamp = "7",
                            Name = "Phone operator",
                            NormalizedName = "PHONE OPERATOR"
                        },
                        new
                        {
                            Id = 6,
                            ConcurrencyStamp = "6",
                            Name = "Sales agent",
                            NormalizedName = "SALES AGENT"
                        },
                        new
                        {
                            Id = 5,
                            ConcurrencyStamp = "5",
                            Name = "Technician",
                            NormalizedName = "TECHNICIAN"
                        });
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 19
                        });
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Sale", b =>
                {
                    b.Property<int>("MeetingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("UpfrontPaymentAmount")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("VerificationNote")
                        .HasMaxLength(210)
                        .HasColumnType("nvarchar(210)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MeetingId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.SalesAgentSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("BeginHour")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeekId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time");

                    b.Property<int>("SalesAgentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesAgentId");

                    b.HasIndex("DayOfWeekId", "BeginHour", "SalesAgentId")
                        .IsUnique();

                    b.ToTable("SalesAgentsSchedules", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.SalesAgentScheduleChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("OldBeginHour")
                        .HasColumnType("time");

                    b.Property<int?>("OldDayOfWeekId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("OldEndHour")
                        .HasColumnType("time");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OldDayOfWeekId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("SalesAgentScheduleChanges_History", (string)null);
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.ClientDebt", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.ClientMeeting", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Clients.Customer", null)
                        .WithOne()
                        .HasForeignKey("WaterFilterBusiness.DAL.Entities.Clients.ClientMeeting", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.Enums.MeetingOutcome", null)
                        .WithMany()
                        .HasForeignKey("MeetingOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PhoneOperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany("ClientMeetings")
                        .HasForeignKey("SalesAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.CustomerCall", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Clients.Customer", null)
                        .WithMany("CallHistory")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.Enums.CallOutcome", null)
                        .WithMany()
                        .HasForeignKey("OutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PhoneAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.CustomerChange", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Clients.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.ScheduledCall", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Clients.Customer", null)
                        .WithOne("ScheduledCall")
                        .HasForeignKey("WaterFilterBusiness.DAL.Entities.Clients.ScheduledCall", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PhoneAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Commission", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Enums.CommissionType", null)
                        .WithMany()
                        .HasForeignKey("CommissionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.CommissionRequest", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Commission", null)
                        .WithOne()
                        .HasForeignKey("WaterFilterBusiness.DAL.Entities.CommissionRequest", "CommissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.BigInventoryItem", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Inventory.InventoryItem", "Tool")
                        .WithOne()
                        .HasForeignKey("WaterFilterBusiness.DAL.Entities.Inventory.BigInventoryItem", "ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.InventoryItemMovement", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Enums.InventoryType", null)
                        .WithMany()
                        .HasForeignKey("FromInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("GiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.Enums.InventoryType", null)
                        .WithMany()
                        .HasForeignKey("ToInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.Inventory.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.InventoryPurchase", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Inventory.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.InventoryRequest", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Enums.InventoryRequestStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.Inventory.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.SmallInventoryItem", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Inventory.InventoryItem", "Tool")
                        .WithOne()
                        .HasForeignKey("WaterFilterBusiness.DAL.Entities.Inventory.SmallInventoryItem", "ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.SmallInventoryRequest", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Inventory.InventoryRequest", "InventoryRequest")
                        .WithOne()
                        .HasForeignKey("WaterFilterBusiness.DAL.Entities.Inventory.SmallInventoryRequest", "InventoryRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryRequest");
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.TechnicianInventoryItem", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.Inventory.InventoryItem", "Tool")
                        .WithOne()
                        .HasForeignKey("WaterFilterBusiness.DAL.Entities.Inventory.TechnicianInventoryItem", "ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Inventory.TechnicianInventoryRequest", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Inventory.InventoryRequest", "InventoryRequest")
                        .WithOne()
                        .HasForeignKey("WaterFilterBusiness.DAL.Entities.Inventory.TechnicianInventoryRequest", "InventoryRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryRequest");
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.RolePermission", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Sale", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Clients.ClientMeeting", "Meeting")
                        .WithOne()
                        .HasForeignKey("WaterFilterBusiness.DAL.Entities.Sale", "MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.Enums.PaymentType", null)
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.SalesAgentSchedule", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Enums.DayOfWeek", null)
                        .WithMany()
                        .HasForeignKey("DayOfWeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.User", "SalesAgent")
                        .WithMany()
                        .HasForeignKey("SalesAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalesAgent");
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.SalesAgentScheduleChange", b =>
                {
                    b.HasOne("WaterFilterBusiness.DAL.Entities.Enums.DayOfWeek", null)
                        .WithMany()
                        .HasForeignKey("OldDayOfWeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFilterBusiness.DAL.Entities.SalesAgentSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.Clients.Customer", b =>
                {
                    b.Navigation("CallHistory");

                    b.Navigation("ScheduledCall");
                });

            modelBuilder.Entity("WaterFilterBusiness.DAL.Entities.User", b =>
                {
                    b.Navigation("ClientMeetings");
                });
#pragma warning restore 612, 618
        }
    }
}
